Completed css brochure form exercise
udaibirv/c1020-code-solutions pull request #15
Opened 2020-10-08 01:27 UTC by udaibirv

<img width="1346" alt="Screen Shot 2020-10-07 at 6 09 31 PM" src="https://user-images.githubusercontent.com/29240758/95404738-b2233580-08ca-11eb-8a91-92e5fd9c4ee3.png">

2020-10-08 18:42 UTC, codingcodymiller requested changes
Yo dude! Yes, as you say, there are some adjustments that can be made to this one. Now that we have discussed it, give this one another go, and I will take a look once you've had a chance to revise it :grin:

2020-10-09 18:17 UTC, codingcodymiller requested changes

2020-10-09 18:17 UTC, codingcodymiller commented on css-brochure-form/styles.css
> +  margin-left: 25rem;
😱 😱 😱 😱 😱 😱 😱 😱 

Margin is meant to be used for minor adjustments, not massive movements like this. Try to accomplish this with another tool such as `text-align` or Flexbox 👍

2020-10-15 01:05 UTC, udaibirv commented on css-brochure-form/styles.css
> +  margin-left: 25rem;
Just attaching screenshots for the changes I made 

<img width="1062" alt="Screen Shot 2020-10-14 at 6 03 52 PM" src="https://user-images.githubusercontent.com/29240758/96061326-ca093500-0e47-11eb-83c0-242c8a3b26df.png">
<img width="292" alt="Screen Shot 2020-10-14 at 6 03 42 PM" src="https://user-images.githubusercontent.com/29240758/96061329-cb3a6200-0e47-11eb-862b-0206302c96f5.png">

2020-10-16 23:13 UTC, codingcodymiller approved these changes

2020-10-26 21:56 UTC, closed without merging